### ISSUE TITLE
Missing source code?

### ISSUE THREAD

**Issue by paulstraw** [versatica/mediasoup-sdp-bridge#1]
Hi there. I'm attempting to set up GStreamer to receive an RTP stream from mediasoup, [as described here](https://mediasoup.org/documentation/v3/communication-between-client-and-server/#consuming-media-in-an-external-endpoint). I believe the last part that needs to be implemented is the SDP offer, and was hoping to use this library to help with that.

It looks like the source code hasn't actually been checked in though. From the package.json, it seems it lives under `lib/`, which doesn't exist on GitHub. Are you planning to add the source, or alternatively, can you point me to any more information on how I might get this mediasoup -> GStreamer flow set up?

Thanks!

**Comment by jmillan** [comment]
This is a work in progress. The implementation is not done yet, will be announced [here](https://mediasoup.discourse.group/c/announcements/) when ready.

Check the *integrations* category in [mediasoup forum](https://mediasoup.discourse.group/c/integration) for more information about GStreamer integration. There are plenty of entries there.
