### ISSUE TITLE
npm security holding package ?

### ISSUE THREAD

**Issue by SylvainSoKette** [versatica/mediasoup-sdp-bridge#5]
Why is this project without any actual implementation suddenly in the npm security holding package registry ?

> This package contained malicious code and was removed from the registry by the npm security team. A placeholder was published to ensure users are not affected in the future.
> 
> Please refer to [www.npmjs.com/advisories?search=mediasoup-sdp-bridge](http://www.npmjs.com/advisories?search=mediasoup-sdp-bridge) for more information.

The link provided redirect to https://github.com/advisories and doesn't actually provide any information.

**Comment by ibc** [comment]
No idea, honestly. Everything looks good now.

**Comment by redoPop** [comment]
I'm seeing the same message [on npm right now:](https://www.npmjs.com/package/mediasoup-sdp-bridge)

> This package contained malicious code and was removed from the registry by the npm security team.
